import './globals.css';
import { Inter } from 'next/font/google'
import Header from './components/header/header';
import styles from './page.module.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body className={`${styles.body_position} ${styles.body_bg}`}>
        <Header/>
        {children}
        </body>
    </html>
  )
}
